/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/house.glb -t
*/

import * as THREE from "three";
import type { JSX } from "react";
import { useEffect, useRef, useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { BvhPhysicsBody } from "@react-three/viverse";
import useWorld from "../../hooks/useWorld";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    house: THREE.Mesh;
    "casing-door": THREE.Mesh;
    door: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    "Material.002": THREE.MeshStandardMaterial;
    "Material.001": THREE.MeshStandardMaterial;
  };
};

const DOOR_OPEN_ANGLE = -Math.PI / 2; // -90 degrees
const LERP_SPEED = 5;
const INTERACT_DISTANCE = 3;

export function House(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/house.glb") as unknown as GLTFResult;
  const doorGroupRef = useRef<THREE.Group>(null);
  const [isOpen, setIsOpen] = useState(false);
  const currentAngle = useRef(0);
  const [canOpen, setCanOpen] = useState(false);
  const doorWorldPos = useRef(new THREE.Vector3());
  const {
    registerDoorInteractable,
    unregisterDoorInteractable,
    characterPosition,
    showMiniMap,
    showLogHistory,
    activeNPCDialog,
  } = useWorld((s: any) => ({
    registerDoorInteractable: s.registerDoorInteractable,
    unregisterDoorInteractable: s.unregisterDoorInteractable,
    characterPosition: s.characterPosition,
    showMiniMap: s.showMiniMap,
    showLogHistory: s.showLogHistory,
    activeNPCDialog: s.activeNPCDialog,
  }));

  useEffect(() => {
    const id = "house-main-door";
    registerDoorInteractable(id, {
      getPosition: () => {
        const v = new THREE.Vector3();
        doorGroupRef.current?.getWorldPosition(v);
        return v;
      },
      onOpen: () => setIsOpen((prev) => !prev),
    });
    return () => {
      unregisterDoorInteractable(id);
    };
  }, [registerDoorInteractable, unregisterDoorInteractable]);

  useFrame((_, delta) => {
    if (!doorGroupRef.current) return;
    const target = isOpen ? DOOR_OPEN_ANGLE : 0;
    currentAngle.current += (target - currentAngle.current) * Math.min(1, LERP_SPEED * delta);
    doorGroupRef.current.rotation.y = currentAngle.current;

    // Update prompt visibility based on player distance
    if (characterPosition) {
      doorGroupRef.current.getWorldPosition(doorWorldPos.current);
      const distance = doorWorldPos.current.distanceTo(characterPosition);
      setCanOpen(distance < INTERACT_DISTANCE);
    } else {
      setCanOpen(false);
    }
  });

  const doorPosition = [-6.538, 2.757, 7.076] as const;

  return (
    <group {...props} dispose={null}>
      {/* House + casing always have collision */}
      <BvhPhysicsBody>
        <mesh
          geometry={nodes.house.geometry}
          material={materials.Material}
          position={[0, 5, 0]}
        />
        <mesh
          geometry={nodes["casing-door"].geometry}
          material={materials["Material.002"]}
          position={[-14.78, 7.757, 1.525]}
        />
      </BvhPhysicsBody>
      {/* When locked (closed): door has collision and blocks entry. Unmount when open so you can enter. */}
      {!isOpen && (
        <BvhPhysicsBody>
          <group position={doorPosition}>
            <mesh geometry={nodes.door.geometry} material={materials["Material.001"]} />
          </group>
        </BvhPhysicsBody>
      )}
      {/* Visual door: animates open/closed, always clickable to toggle */}
      <group ref={doorGroupRef} position={doorPosition}>
        <mesh
          geometry={nodes.door.geometry}
          material={materials["Material.001"]}
          position={[0, 0, 0]}
          onClick={(e) => {
            e.stopPropagation();
            setIsOpen((prev) => !prev);
          }}
          onPointerOver={(e) => {
            e.stopPropagation();
            document.body.style.cursor = "pointer";
          }}
          onPointerOut={() => {
            document.body.style.cursor = "default";
          }}
        />
        {canOpen && !showMiniMap && !showLogHistory && !activeNPCDialog && (
          <Html position={[0, 2, 0]} center>
            <div
              style={{
                background: "rgba(0,0,0,0.75)",
                padding: "6px 10px",
                borderRadius: "6px",
                color: "#fff",
                fontSize: "13px",
                cursor: "pointer",
                whiteSpace: "nowrap",
              }}
              onClick={() => setIsOpen((prev) => !prev)}
            >
              {isOpen ? "Close (F)" : "Open (F)"}
            </div>
          </Html>
        )}
      </group>
    </group>
  );
}

useGLTF.preload("/models/house.glb");
